repos:
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
        args: [
          --config=pyproject.toml,
          --preview
        ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.247'
    hooks:
      - id: ruff
        args: [
          --fix,
          --show-fixes
        ]

